sonar.projectName=Chatbot-agentic-RAG
sonar.sourceEncoding=UTF-8
sonar.sources=app
sonar.coverage.exclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx,**/*.css,**/*.html,app/frontend/**
sonar.exclusions=tests/,faiss_Hugging_index/,**/*.pyc
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
